name: CD - Deploy to Production
on:
  push:
    branches: [main]

env:
  NODE_VERSION: '22.x'
  WORKING_DIR: '/home/quan/multi-vendor-api'

jobs:
  quick-check:
    name: Quick Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      - run: npm ci --only=production
      - run: npx prisma generate
      - run: npm run build

  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: quick-check
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
      - run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts
      - name: Deploy to VPS
        env:
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_USER: ${{ secrets.VPS_USER }}
          VPS_PORT: ${{ secrets.VPS_PORT }}
          WORKING_DIR: ${{ env.WORKING_DIR }}
        run: |
          ssh -p $VPS_PORT $VPS_USER@$VPS_HOST << 'ENDSSH'
            set -e
            cd $WORKING_DIR
            git fetch origin main
            git reset --hard origin/main
            npm ci --only=production
            npx prisma generate
            npx prisma migrate deploy
            npm run build
            pm2 restart multi-vendor --update-env || pm2 start ecosystem.config.js --env production
            pm2 save
          ENDSSH
