name: CD - Deploy to Production
on:
  push:
    branches: [main]

env:
  NODE_VERSION: '22.x'
  PROJECT_NAME: 'multi-vendor-api'
  WORKING_DIR: '/home/quan/multi-vendor-api'

jobs:
  quick-check:
    name: Quick Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      - run: npm ci
      - run: npx prisma generate
      - run: npm run build

  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: quick-check
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}

      - name: Add host key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to VPS
        env:
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_USER: ${{ secrets.VPS_USER }}
          VPS_PORT: ${{ secrets.VPS_PORT }}
          PROJECT_NAME: ${{ env.PROJECT_NAME }}
          WORKING_DIR: ${{ env.WORKING_DIR }}
        run: |
          ssh -p $VPS_PORT $VPS_USER@$VPS_HOST "PROJECT_NAME=$PROJECT_NAME WORKING_DIR=$WORKING_DIR bash ~/deploy.sh"
